// import { Inter } from 'next/font/google'
import './component/style/globals.css'

import { Container } from "@mui/material";
import Appbar from "./component/shared/Appbar";
import ThemeRegistry from "./component/style/ThemeRegistry";
import Footer from './component/shared/Footer';
// import Appbar from './component/shared/Appbar';
// import { Container } from '@mui/material';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body className={inter.className}>{children}</body>
// //     </html>
// //   )
// // }

// export default function RootLayout(props) {
//   const { children } = props;
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//       <ThemeRegistry options={{ key: 'mui' }}>
//       <Appbar/>

//       {children}
      
//       </ThemeRegistry>
//       </body>
//     </html>
//   );
// }

export default function RootLayout(props) {
  const { children } = props;
  return (
    <html lang="en">
      <body  style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }} >
      <ThemeRegistry options={{ key: 'mui' }}>
      
         <Appbar/>
         <div style={{ flex: 1 }}>
         {children}
         </div>
        <Footer/>
        </ThemeRegistry>
      </body>
    </html>
  );
}