export {default as Folly} from './folly.png'
export {default as Logo} from './follyLogo.png'
export {default as LogoWhite} from './logowhite.png'
export {default as Follyb} from './fo.png'
export { default as frondendDev} from './frontendDev.jpg'
export { default as frondendTech} from './frontendTech.jpg'
export { default as fullstack} from './fullStack.jpg'
export { default as seo} from './seo.jpg'
export { default as SEO} from './seo-1.jpg'
export { default as Web3} from './web3.jpg'
export { default as Airdrop} from './Airdrop_Calculator.png'
export { default as defi} from './deficonnect.png'
export { default as dyleumTestnet} from './Dyleum_Testnet.png'
export { default as dyleum} from './dyleum.png'
export { default as food} from './Food_Website.png'
export { default as present} from './Presentation_Ai.png'
export { default as solak} from './SolakGpt.png'
export { default as staking} from './staking.png'
export { default as follyhub} from './follyhub.png'
// export { default as food} from './web3.jpg'
